config/routes.rb
Rails.application.routes.draw do
  resources :teams do
    resources :players
  end

  get 'event_source/:projection/:event' => 'event_source#projected', as: 'event_source'

end

app/models/player.rb
class Player < ActiveRecord::Base
  self.table_name = 'players'
  belongs_to :team
end

app/models/team.rb
class Team < ActiveRecord::Base
  self.table_name = 'teams'
  has_many :players
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/concerns/event_source.rb
module EventSource
  extend ActiveSupport::Concern
  EVENT_ID_KEY = :event_id

  included do
    helper_method :read_and_clear_event_id
  end
  
  def read_and_clear_event_id
    session.delete EVENT_ID_KEY
  end

  def store_event_id(event_id)
    session[EVENT_ID_KEY] = event_id
  end
end

app/controllers/event_source_controller.rb
class EventSourceController < ApplicationController
  include ActionController::Live

  def projected
    response.headers['Content-Type'] = 'text/event-stream'
    sse = ActiveEvent::SSE.new(response.stream)
    ActiveEvent::EventSourceServer.wait_for_event_projection event_id, projection, timeout: 10
    sse.event('projected')
  rescue IOError
    # ignore disconnect
  rescue ActiveEvent::ProjectionException => e
    sse.event('exception', {error: e.message, backtrace: e.backtrace})
  ensure
    sse.close
  end

  private

  def event_id
    params[:event].to_i
  end

  def projection
    params[:projection]
  end
end

app/controllers/players_controller.rb
class PlayersController < ApplicationController
  include EventSource
  before_action :team

  def index
    @players = Player.all
  end

  def show
    @player = Player.find(id_param)
  end

  def new
    @player = CreatePlayerCommand.new(team_id: team_id_param) 
    @player.team_id = params[:team_id]
  end

  def edit
    @player = UpdatePlayerCommand.new Player.find(id_param).attributes
  end

  def create
    @player = CreatePlayerCommand.new player_params.merge(team_id: team_id_param)
    if store_event_id Domain.run_command(@player)
      redirect_to team_players_path(@team), notice: 'Player was successfully created.'
    else
      render action: 'new'
    end
  end

  def update
    @player = UpdatePlayerCommand.new player_params.merge(id: id_param)
    if store_event_id Domain.run_command(@player)
      redirect_to team_players_path(@team), notice: 'Player was successfully updated.'
    else
      render action: 'edit'
    end
  end

  def destroy
    delete_player = DeletePlayerCommand.new(id: id_param)
    if store_event_id Domain.run_command(delete_player)
      redirect_to team_players_url(@team), notice: 'Player was successfully destroyed.'
    else
      redirect_to team_playerurl(@team), alert: 'Player could not be deleted.'
    end
  end

  private

  def player_params
    params.require(:player).permit(:name, :position, :number, :team_id)
  end

  def id_param
    params.require(:id).to_i
  end

  def team_id_param
    params.require(:team_id).to_i
  end

  def team
    @team = Team.find(team_id_param)
  end
end

app/controllers/teams_controller.rb
class TeamsController < ApplicationController
  include EventSource

  def index
    @teams = Team.all
  end

  def show
    @team = Team.find(id_param)
  end

  def new
    @team = CreateTeamCommand.new
  end

  def edit
    @team = UpdateTeamCommand.new Team.find(id_param).attributes
  end

  def create
    @team = CreateTeamCommand.new team_params
    if store_event_id Domain.run_command(@team)
      redirect_to @team, notice: 'Team was successfully created.'
    else
      render action: 'new'
    end
  end

  def update
    @team = UpdateTeamCommand.new team_params.merge(id: id_param)
    if store_event_id Domain.run_command(@team)
      redirect_to @team, notice: 'Team was successfully updated.'
    else
      render action: 'edit'
    end
  end

  def destroy
    delete_team = DeleteTeamCommand.new(id: id_param)
    if store_event_id Domain.run_command(delete_team)
      redirect_to teams_url, notice: 'Team was successfully destroyed.'
    else
      redirect_to team_url(id: id_param), alert: 'Team could not be deleted.'
    end
  end

  private

  def team_params
    params.require(:team).permit(:name, :age, :gender)
  end

  def id_param
    params.require(:id).to_i
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/event_source_helper.rb
module EventSourceHelper
  def event_source(projection)
    ActiveEvent::EventSourceServer.fail_on_projection_error(projection)
    event_id = read_and_clear_event_id
    if event_id
      content_tag(:div, '',
                  class: 'event-source',
                  data: {href: event_source_path(projection: projection, event: event_id)})
    end
  end
end

app/helpers/players_helper.rb
module PlayersHelper
end

app/helpers/teams_helper.rb
module TeamsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>TeamBuilder</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <% flash.each do |name, msg| %>
    <%= content_tag :div, msg, class_name: name %>
  <% end %>
<%= yield %>

</body>
</html>

app/views/players/_form.html.erb
<%= form_for([ @team, @player ]) do |f| %>
  <% if @player.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@player.errors.count, "error") %> prohibited this player from being saved:</h2>

      <ul>
      <% @player.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :position %><br>
    <%= f.text_field :position %>
  </div>
  <div class="field">
    <%= f.label :number %><br>
    <%= f.number_field :number %>
  </div>
  <div class="field" style='display:none'>
    <%= f.label :team_id %><br>
    <%= f.text_field :team_id %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/players/edit.html.erb
<h1>Editing player</h1>

<%= render 'form' %>

<%= link_to 'Show', @player %> |
<%= link_to 'Back', players_path %>

app/views/players/index.html.erb
<%= event_source('PlayerProjection') %>
<h1>Listing Players for <%= @team.name %></h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Position</th>
      <th>Number</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @players.each do |player| %>
      <tr>
        <td><%= player.name %></td>
        <td><%= player.position %></td>
        <td><%= player.number %></td>
        <td><%= link_to 'Show', team_player_path(@team, player) %></td>
        <td><%= link_to 'Edit', edit_team_player_path(@team, player) %></td>
        <td><%= link_to 'Destroy', team_player_path(@team, player), method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Player', new_team_player_path(@team) %>

app/views/players/new.html.erb
<h1>New player</h1>

<%= render 'form' %>

<%= link_to 'Back', team_players_path(@team) %>

app/views/players/show.html.erb
<%= event_source('PlayerProjection') %>
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @player.name %>
</p>

<p>
  <strong>Position:</strong>
  <%= @player.position %>
</p>

<p>
  <strong>Number:</strong>
  <%= @player.number %>
</p>

<p>
  <strong>Team:</strong>
  <%= @player.team %>
</p>

<%= link_to 'Edit', edit_team_player_path(@team,@player) %> |
<%= link_to 'Back', team_players_path(@team) %>